ALPACA_API_KEY = 'PK3VO5HP6LZRGBVGZZQNNUC7RH'
ALPACA_SECRET_KEY = "A53bMGBHVbWsvM3smmZ8cK5vPYBDANgmG6DxgCvdDdwR"

KAFKA_BROKER = "localhost:9092"
RAW_TOPIC = "stockdata"
ALERT_TOPIC = "fraudalerts"

SYMBOLS = ["AAPL", "MSFT", "TSLA"]
